name: 'debug'

on: # rebuild any PRs and main branch changes
  push:
    branches:
      - debug

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
      - run: |
          wget -qq https://github.com/QiYuTechDev/seo/releases/download/0.7.0/seo_amd64.deb
      - run: |
          sudo dpkg -i seo_amd64.deb
      - run: |
          sudo apt update
      - run: |
          sudo apt install --fix-broken -y
      - run: |
          sudo snap install chromium-ffmpeg
      - run: |
          sudo ln -s /snap/chromium-ffmpeg/current/chromium-ffmpeg-104195/chromium-ffmpeg/libffmpeg.so /usr/lib/x86_64-linux-gnu/libffmpeg.so
      - run: |
          wget -qq https://repo.mongodb.org/apt/ubuntu/dists/focal/mongodb-org/5.0/multiverse/binary-amd64/mongodb-org-server_5.0.3_amd64.deb
      - run: |
          sudo dpkg -i mongodb-org-server_5.0.3_amd64.deb
      - run: |
          sudo apt install -y xpra
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
