name: 'windows'

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Node Modules
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: Install Package
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Run All Test
        run:  npm run all

      - uses: ./
        with:
          version: "0.7.0"
          url: "https://news.ycombinator.com/"
          pdf: true
          snapshot: true
          rrweb: true
          debug: true
